# Lab01: Basic Numpy Operations

In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Declaring vectors & matrices

In [3]:
u = np.array([[2], [-7], [1]])
v = np.array([[-3], [0], [4]])
A = np.array([[1, 2, 0], [3, -1, 4]])
B = np.array([[2, -1], [1, 0], [-3, 4]])

### Basic Numpy Operations

In [4]:
qA = u + v
qA

array([[-1],
       [-7],
       [ 5]])

In [6]:
qB = -3 * u
qB

array([[-6],
       [21],
       [-3]])

In [28]:
qC = u.T.dot(v)
qC

array([[-2]])

We typically write $ uv $ instead of $ u^Tv$ because it is more readable, and reduces notational clutter. The transpose is implied by the operation.

In [16]:
qD = u.T.dot(u)
qD

array([[54]])

In [17]:
qE = np.sqrt(qD)
qE

array([[7.34846923]])

In [20]:
qF = u * v  # hadamard product
qF

array([[-6],
       [ 0],
       [ 4]])

In [21]:
qG = A + A
qG

array([[ 2,  4,  0],
       [ 6, -2,  8]])

In [22]:
qH = A + u
qH

ValueError: operands could not be broadcast together with shapes (2,3) (3,1) 

Question H is impossible because the matrix and vector do not have the same dimensions

In [24]:
qI = 10 * A
qI

array([[ 10,  20,   0],
       [ 30, -10,  40]])

In [25]:
qJ = A.dot(v)
qJ

array([[-3],
       [ 7]])

In [26]:
qK = A.dot(B)
qK

array([[ 4, -1],
       [-7, 13]])

In [27]:
qL = A.T
qL

array([[ 1,  3],
       [ 2, -1],
       [ 0,  4]])

In [32]:
qM = A.dot(A.T)
qM

array([[ 5,  1],
       [ 1, 26]])

In [33]:
qN = A.T.dot(A)
qN

array([[10, -1, 12],
       [-1,  5, -4],
       [12, -4, 16]])

In [39]:
qO = u.min()
qO

-7

In [43]:
qP = u.argmin()
qP

1

In [44]:
qQ = u.mean()
qQ

-1.3333333333333333

## Q2: ```cumsum```

In [46]:
x = np.array(list(range(1, 5)))

x.cumsum()

array([ 1,  3,  6, 10])

In [51]:
def my_cumsum(l1: list):
    return [curr := (curr if "curr" in locals() else 0) + x for x in l1]

In [52]:
my_cumsum(x)

[1, 3, 6, 10]

In [61]:
def dereks_cumsum(l1: list):
    total = 0
    NewList = [None] * len(l1)
    for x in range(len(l1)):
        total += l1[x]
        NewList[x] = total
    return NewList

In [62]:
%timeit dereks_cumsum(x)

383 ns ± 2.35 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [58]:
%timeit my_cumsum(x)

839 ns ± 6.91 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [64]:
%timeit np.cumsum(x)

787 ns ± 3.24 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
